### ISSUE TITLE
Add support for sending an email on initial pending purchases

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-checks-gateway#1]
People want to be able to send an email with the details on where to send checks and such. Apparently the confirmation page message isn't enough. I've seen 3-4 tickets on this in the last 2 days.

**Comment by pippinsplugins** [comment]
I've wanted to get this added for a long time.

@mindctrl Want to take a stab at it?

**Comment by mindctrl** [comment]
@pippinsplugins sure. We want this to be a separate text/setting, right?

**Comment by pippinsplugins** [comment]
Yes I think so.

**Comment by mindctrl** [comment]
@pippinsplugins updated per your comment. Do you want a setting for the heading here? Want any actions or filters in there?

**Comment by pippinsplugins** [comment]
Yes let's add a setting for the header, or perhaps it should just match the subject?

Filters please.

**Comment by mindctrl** [comment]
@pippinsplugins updated PR with a setting for heading and reverting back to EDD() instance for emails class per our conversation.

Do we still need filters here since we're using the emails class? If so, what would you like to see?

**Comment by pippinsplugins** [comment]
Since they're using `edd_get_option()`, they already get passed through a filter.

**Comment by pippinsplugins** [comment]
This looks good to me. I'll test once more and release on Monday or Tuesday
