### ISSUE TITLE
Admin emails are going to customer instead of admin

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-checks-gateway#10]
In #8 an admin notification email was added, but it is set to send to the customer instead of the admin.

**Comment by mintplugins** [comment]
@SDavisMedia This look okay to you?

**Comment by SDavisMedia** [comment]
@mintplugins Blah! That's what happens when your admin email and your purchase email go to the same inbox. Good catch. Tested and confirmed all good here. Thanks. :+1:
