### ISSUE TITLE
UI for editing pending sale email template

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-checks-gateway#8]
This is something I'd like to see for all extensions that send out emails. This gateway sends an email out for new pending sales and it can only be edited [using a filter](https://github.com/easydigitaldownloads/edd-checks-gateway/blob/master/edd-checks-gateway.php#L136). Some users are even confused thinking they can edit the default EDD Sale Notification email template to edit this one.

**Comment by SDavisMedia** [comment]
had a request for this today

**Comment by SDavisMedia** [comment]
@cklosowski This issue is the reason for my question: https://cl.ly/3d053q1K2N1k

I don't think I'm a big fan of that system, as it has me feeling like unnecessary tags are available for this email. But it also doesn't make sense (IMO) to continuously rebuild the same email tags across extensions just to exclude certain extension related tags. I don't know.

Anyway, can you check this out please?

**Comment by cklosowski** [comment]
Code looks good, going to run  a few tests and report back.

**Comment by cklosowski** [comment]
Test look good, nice work @SDavisMedia
